### PR TITLE
Enable building Linux packages

### PR DESCRIPTION
**Pull request by Nicky-D**

### CODE REVIEW

**Comment by Nicky-D** [comment]
@vir-linden / @nat-goodspeed this PR is sitting around without even much as a single peep for nearly a week now.
I need those builds as input for other PRs otherwise I've to roll my own under my GitHub account, which I'd like to avoid if possible. 

Is there any ETA when PRs are acted on?

**Comment by nat-goodspeed** [comment]
I didn't see anything about it until you tagged me. I see you've tagged me for five other repos too. Looking now.

**Review by nat-goodspeed — APPROVED** [review]

**Comment by Nicky-D** [comment]
> I didn't see anything about it until you tagged me. I see you've tagged me for five other repos too. Looking now.

Thank you @nat-goodspeed. 

I have a feeling those reviews not in viewer can easily end in limbo. As it is also impossible to select a reviewer or assignee. Having to single someone out and call for attention didn't feel like the right process, but at least it worked. 
If you could pretty please create a version tag in those repositories, so a release is created? (and then I'd could look at packages like colladom)

**Comment by nat-goodspeed** [comment]
> As it is also impossible to select a reviewer or assignee.

? If there's a GitHub permissions thing we should fix, let's fix it for the autobuild package repositories. But I don't know what it is.

> If you could pretty please create a version tag in those repositories

Coming up.

**Comment by Nicky-D** [comment]
> > As it is also impossible to select a reviewer or assignee.
> 
> ? If there's a GitHub permissions thing we should fix, let's fix it for the autobuild package repositories. But I don't know what it is.

I have been perusing the docs. One cannot assign a reviewer or assignee unless they got write access to the repository.
So I suppose the easy workflow is out of the window. Maybe there is some setting, but for now I'll just ping a poor soul.

> 
> > If you could pretty please create a version tag in those repositories
> Coming up.

Thank you. You're the best

**Pull request merged**
